### PR TITLE
remove force unwrap, https://github.com/gizmosachin/VolumeBar/issues/21

### PR DESCRIPTION
**Pull request by piemonte**

### CODE REVIEW

**Comment by gizmosachin** [comment]
👍

**Comment by gizmosachin** [comment]
thanks!

**Review by piemonte — COMMENTED** [review]
👍

**Review by gizmosachin — APPROVED** [review]
👌

**Comment by gizmosachin** [comment]
(waiting for CI just in case)

**Comment by gizmosachin** [comment]
pushed to pods!

**Pull request merged**
